name: Maven CI


on:
  push:
  pull_request:

jobs:
  build:
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B package